# Generated by Django 5.1.3 on 2025-06-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0003_empresas_estado_monitoreo_empresas_nivel_seguridad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionMonitoreo',
        ),
    ]
