# Generated by Django 5.1.3 on 2025-06-23 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0004_delete_configuracionmonitoreo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForoCiberseguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Problema')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada')),
                ('categoria', models.CharField(choices=[('MALWARE', 'Malware'), ('PHISHING', 'Phishing'), ('RANSOMWARE', 'Ransomware'), ('DOS', 'Denegación de Servicio'), ('INTRUSION', 'Intrusión'), ('ROBO_DATOS', 'Robo de Datos'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Análisis'), ('ANALIZADO', 'Analizado'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], default='PENDIENTE', max_length=20)),
                ('analisis_stanza', models.JSONField(blank=True, null=True, verbose_name='Análisis de Stanza')),
                ('tipo_ataque_detectado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Ataque Detectado')),
                ('confianza_analisis', models.FloatField(blank=True, null=True, verbose_name='Confianza del Análisis (%)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_analisis', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_foro', to='Crud.empresas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_foro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte del Foro',
                'verbose_name_plural': 'Reportes del Foro',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('es_solucion', models.BooleanField(default=False, verbose_name='¿Es una solución?')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_detalle', to='Crud.forociberseguridad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta del Foro',
                'verbose_name_plural': 'Respuestas del Foro',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='forociberseguridad',
            name='respuestas',
            field=models.ManyToManyField(blank=True, related_name='reporte_principal', to='Crud.respuestaforo'),
        ),
    ]
