# Generated by Django 5.1.3 on 2025-06-30 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crud', '0005_forociberseguridad_respuestaforo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroactividad',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='Crud.empresas'),
        ),
    ]
